USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE WID_HACKATHON;
CREATE OR REPLACE SCHEMA DATA;
CREATE OR REPLACE WAREHOUSE WID_COMPUTE_WH WITH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60 -- Suspends the queries after 60 secs of inactivity to stop credit usage
  AUTO_RESUME = TRUE; 

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE RESOURCE MONITOR WID_HACKATHON_RM
  WITH CREDIT_QUOTA = 50
  TRIGGERS ON 75 PERCENT DO SUSPEND
           ON 100 PERCENT DO SUSPEND_IMMEDIATE;      
ALTER ACCOUNT SET RESOURCE_MONITOR = WID_HACKATHON_RM;